version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    env_file:
      - .env.docker
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: